development:
  adapter: mysql2
  encoding: utf8
  database: SiteAboutNmsutton
  pool: 5
  timeout: 5000
  username: root
  password: pa$$word

test:
  adapter: mysql2
  encoding: utf8
  database: SiteAboutNmsutton
  pool: 5
  timeout: 5000
  username: root
  password: pa$$word